In [74]:
import pandas as pd
import numpy as np

In [97]:
CHAT=pd.read_csv('C:/Users/miavila/Desktop/CRUCE SCORE/DICIEMBRE/CHAT TOTAL.csv')
CHAT=pd.DataFrame(CHAT,columns=['Fecha', 'Cola', 'Conclusión', 'Etiqueta externa', 'Manejo total',
       'Mes'])

In [98]:
CHAT.rename(columns={'Etiqueta externa':'Cedula'},inplace=True)

In [131]:
CHAT

,Fecha,Cola,Conclusión,Cedula,Manejo total,Mes
0,2022-02-25 22:04:00,Chat Persona Natural Publica,Información General - Características de produ...,-1,00:06:07.203,2
1,2022-02-25 22:10:00,Chat Persona Natural Publica,Información General - Características de produ...,-1,00:04:00.544,2
2,2022-02-26 00:01:00,Chat Persona Natural Publica,Proceso de apertura de cuentas pensionados - SV,-1,00:14:51.130,2
3,2022-02-26 00:48:00,Chat Persona Natural Publica; Chat Persona Nat...,Monitoreo desbloqueo de productos - SV; Apertu...,-1,01:47:55.877,2
4,2022-02-26 02:08:00,Chat Persona Natural Publica,Saldos y movimientos aclaración - SV,-1,00:17:10.013,2
...,...,...,...,...,...,...
1575615,2022-11-30 23:56:00,Chat Persona Natural Publica,Cliente nunca escribió - SV,32091374,00:05:35.199,11
1575616,2022-11-30 23:57:00,Chat Persona Natural Privada; Chat Persona Nat...,NaN,1102873963,NaN,11
1575617,2022-11-30 23:57:00,Chat Persona Natural Privada,NaN,1102575650,NaN,11
1575618,2022-11-30 23:57:00,Chat Persona Natural Publica,NaN,1127956064,NaN,11
1575619,2022-11-30 23:58:00,Chat Persona Natural Privada; Chat Persona Nat...,Bloqueo Tarjeta débito,1108935671,00:03:58.590,11

In [108]:
clien=pd.read_excel('C:/Users/miavila/Desktop/CRUCE SCORE/DICIEMBRE/base_clientes_banco.csv.xlsx')
clien=pd.DataFrame(clien,columns=['nro_identificacion', 'cliente_bancario', 'segmento_digital',
       'score_integral'])

In [112]:
clien

         nro_identificacion cliente_bancario segmento_digital score_integral
0              9.590600e+04               SI          DIGITAL            8.0
1              9.590600e+04               SI          DIGITAL            8.0
2              1.298110e+05               SI          DIGITAL           13.0
3              1.298110e+05               SI          DIGITAL           13.0
4              1.298110e+05               SI          DIGITAL           13.0
...                     ...              ...              ...            ...
1481921        2.000006e+09               SI          DIGITAL      SIN SCORE
1481922        2.000009e+09               SI     SIN SEGMENTO      SIN SCORE
1481923        2.000009e+09               SI     SIN SEGMENTO      SIN SCORE
1481924        2.000011e+09               SI     SIN SEGMENTO      SIN SCORE
1481925        2.000011e+09               SI     SIN SEGMENTO      SIN SCORE

[1481926 rows x 4 columns]

In [111]:
clien.dropna(inplace=True)

In [113]:
#
clien.rename(columns={'nro_identificacion':'Cedula'},inplace=True)
clien['Cedula']=clien['Cedula'].astype(int)

In [115]:
clien.drop_duplicates(subset=['Cedula'],keep='last', inplace=True)

In [117]:
CHAT.Cedula.replace(np.nan,-1,inplace=True)

In [119]:
import re 
def extraer_tratamiento(name):
  m = re.search(r"\w+\.",str(name))
  if not m:
      return -1 # CON CARATERES *
  return m[0][:-1]

In [120]:
CHAT['Cedula']=CHAT['Cedula'].apply(extraer_tratamiento)

In [121]:
CHAT['Cedula']=CHAT['Cedula'].astype(np.int64)

In [133]:


nueva_fila2 = {'Cedula':-1, 'cliente_bancario':np.nan, 'segmento_digital':np.nan, 'score_integral':np.nan}

#Añadiendo una fila al dataframe
clien =clien.append(nueva_fila2, ignore_index=True)

C:\Users\miavila\AppData\Local\Temp\ipykernel_21304\2452310141.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  clien =clien.append(nueva_fila2, ignore_index=True)

In [135]:
df=pd.merge(CHAT,clien,on=['Cedula'])

In [136]:
df

,Fecha,Cola,Conclusión,Cedula,Manejo total,Mes,cliente_bancario,segmento_digital,score_integral
0,2022-02-25 22:04:00,Chat Persona Natural Publica,Información General - Características de produ...,-1,00:06:07.203,2,NaN,NaN,NaN
1,2022-02-25 22:10:00,Chat Persona Natural Publica,Información General - Características de produ...,-1,00:04:00.544,2,NaN,NaN,NaN
2,2022-02-26 00:01:00,Chat Persona Natural Publica,Proceso de apertura de cuentas pensionados - SV,-1,00:14:51.130,2,NaN,NaN,NaN
3,2022-02-26 00:48:00,Chat Persona Natural Publica; Chat Persona Nat...,Monitoreo desbloqueo de productos - SV; Apertu...,-1,01:47:55.877,2,NaN,NaN,NaN
4,2022-02-26 02:08:00,Chat Persona Natural Publica,Saldos y movimientos aclaración - SV,-1,00:17:10.013,2,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
1503877,2022-11-30 23:52:00,Chat Persona Natural Privada,"Clave virtual - asignación, bloqueo y desbloqu...",28403082,00:10:57.836,11,SI,SIN SEGMENTO,6.0
1503878,2022-11-30 23:53:00,Chat Persona Natural Publica,"Clave virtual - asignación, bloqueo y desbloqu...",1128394243,00:11:27.068,11,SI,ANALOGO,7.0
1503879,2022-11-30 23:53:00,Chat Persona Natural Privada,NaN,1016110015,NaN,11,SI,DIGITAL,6.0
1503880,2022-11-30 23:54:00,Chat Persona Natural Privada; Chat Persona Nat...,Actualización de datos - SV,1004598454,00:12:58.333,11,SI,DIGITAL,5.0
1503881,2022-11-30 23:55:00,Chat Persona Natural Publica,Cliente nunca escribió - SV,1050945233,00:05:10.376,11,SI,DIGITAL,6.0

In [137]:
df.Cedula.replace(-1,np.nan,inplace=True)

In [138]:
df

,Fecha,Cola,Conclusión,Cedula,Manejo total,Mes,cliente_bancario,segmento_digital,score_integral
0,2022-02-25 22:04:00,Chat Persona Natural Publica,Información General - Características de produ...,NaN,00:06:07.203,2,NaN,NaN,NaN
1,2022-02-25 22:10:00,Chat Persona Natural Publica,Información General - Características de produ...,NaN,00:04:00.544,2,NaN,NaN,NaN
2,2022-02-26 00:01:00,Chat Persona Natural Publica,Proceso de apertura de cuentas pensionados - SV,NaN,00:14:51.130,2,NaN,NaN,NaN
3,2022-02-26 00:48:00,Chat Persona Natural Publica; Chat Persona Nat...,Monitoreo desbloqueo de productos - SV; Apertu...,NaN,01:47:55.877,2,NaN,NaN,NaN
4,2022-02-26 02:08:00,Chat Persona Natural Publica,Saldos y movimientos aclaración - SV,NaN,00:17:10.013,2,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
1503877,2022-11-30 23:52:00,Chat Persona Natural Privada,"Clave virtual - asignación, bloqueo y desbloqu...",2.840308e+07,00:10:57.836,11,SI,SIN SEGMENTO,6.0
1503878,2022-11-30 23:53:00,Chat Persona Natural Publica,"Clave virtual - asignación, bloqueo y desbloqu...",1.128394e+09,00:11:27.068,11,SI,ANALOGO,7.0
1503879,2022-11-30 23:53:00,Chat Persona Natural Privada,NaN,1.016110e+09,NaN,11,SI,DIGITAL,6.0
1503880,2022-11-30 23:54:00,Chat Persona Natural Privada; Chat Persona Nat...,Actualización de datos - SV,1.004598e+09,00:12:58.333,11,SI,DIGITAL,5.0
1503881,2022-11-30 23:55:00,Chat Persona Natural Publica,Cliente nunca escribió - SV,1.050945e+09,00:05:10.376,11,SI,DIGITAL,6.0

In [139]:
df.to_csv('cruce chat_base &  Clientes.csv')