In [2]:
#! pip install --upgrade pip
import pandas as pd
import numpy as np
#%pip install re
import re

para error (ValueError: Cannot mask with non-boolean array containing NA / NaN values)
+ usar na=True
+ ejemplo .str.contains('EXpRESs',case=False,na=True)]

## Carga del Set de datos

In [8]:
# ruta de kernelB donde se almacenara las bases depuradas
kernelB='C://Users//miavila//Desktop//SCRIPS  - ALEX/'
df=pd.read_csv(kernelB +'UNIFICACIÓN 2018-2022.csv',low_memory=False)
#enero 2021- septiembre 2022
df=pd.DataFrame(df,columns=['Fecha', 'Usuario', 'Numero de Cedula', 'Producto', 'Motivos', 'ID',
       'Marca en el extarior', 'Año', 'MesN', 'Dia_MesN'] )
df.rename(columns={'Marca en el extarior':'Marca en el exterior'},inplace=True)
df

,Fecha,Usuario,Numero de Cedula,Producto,Motivos,ID,Marca en el exterior,Año,MesN,Dia_MesN
0,2018-06-05,leidyj.rodriguezd@davivienda.com,80865792,Tarjetas de Crédito,"Certificaciónes, extractos y Paz y Salvos",NaN,NaN,2018,6,5
1,2018-06-05,jeysonf.buitrago@davivienda.com,1014193850,Tarjetas de Crédito,"Aclaración Saldos, Movimientos y estado de Pro...",NaN,NaN,2018,6,5
2,2018-06-05,jeysonf.buitrago@davivienda.com,1090450755,Tarjetas de Crédito,Otras Solicitudes,NaN,NaN,2018,6,5
3,2018-06-05,jeysonf.buitrago@davivienda.com,32317050,Tarjetas de Crédito,"Certificaciónes, extractos y Paz y Salvos",NaN,NaN,2018,6,5
4,2018-06-05,jeysonf.buitrago@davivienda.com,51898447,Tarjetas de Crédito,"Aclaración Saldos, Movimientos y estado de Pro...",NaN,NaN,2018,6,5
...,...,...,...,...,...,...,...,...,...,...
13502785,2022-10-31,llvarvar@proveedores.davivienda.com,17773627.0,Cuentas de ahorros tradicional y corriente,Estado del producto - SV,019a0341d7dae18e,NaN,2022,10,31
13502786,2022-10-31,wendynope@proveedores.davivienda.com,8785001.0,Canales virtuales,"Clave virtual - asignación, bloqueo y desbloqu...",na,NaN,2022,10,31
13502787,2022-10-31,llvarvar@proveedores.davivienda.com,16986708.0,Cuentas de ahorros tradicional y corriente,Estado del producto - SV,01d4034376e856fd,NaN,2022,10,31
13502788,2022-10-31,wendynope@proveedores.davivienda.com,79596885.0,Tarjeta de Crédito,Saldos y movimientos aclaración - SV,na,NaN,2022,10,31
13502789,2022-10-31,llvarvar@proveedores.davivienda.com,39792341.0,Cuentas de ahorros tradicional y corriente,Saldos y movimientos aclaración - SV,01d4034376e85701,NaN,2022,10,31

In [42]:
df.Producto.unique()

array(['Tarjetas de Crédito', 'Credíto Hipotecario',
       'Cuentas de Ahorro - Corriente', 'Seguros', 'Tarjeta E-card',
       'Crédito de Libranza', 'Crediexpress Rotativo',
       'Leasing Bolívar - Confinanciera', 'Leasing Inmobiliario',
       'CDT - CDAT', 'Crédito de Vehiculo', 'Cuenta Movil', 'FICS',
       'Productos de Inversión', 'Daviplata', 'Credito Móvil',
       'No Aplica', 'Tarjeta de credito', nan, 'Tarjeta de Credito',
       'No aplica', 'Cuenta de ahorros', 'Cuenta AFC',
       'Canales virutales', 'Credito hipotecario', 'CDT',
       'Cuenta Corriente', 'Credito fijo', 'Credito movil',
       'Credito de vehiculo', 'Tarjeta Debito', 'Leasing',
       'Otros servicios', 'Credito libranza', 'E card', 'CDAT',
       'Otras solicitudes', 'Otras Solicitudes',
       'Rediferido y Cambio de Diferido', 'Productos de Inversion',
       'Leasing confinanciera', 'Cuenta movil', 'Cancelación',
       'Libranza movil', 'Adelanto de nomina', 'Tarjeta movil',
       'Tarjeta_de_Credito', 'Cuenta_de_ahorros', 'Tarjeta_Debito',
       'No_aplica', 'Fondo_virtual', 'Canales_virutales',
       'Otros_servicios', 'Credito_de_vehiculo', 'Credito_fijo',
       'Credito_hipotecario', 'E_card', 'Tarjeta_movil',
       'Cuenta_Corriente', 'Adelanto_de_nomina', 'Crediexpress_Rotativo',
       'Cuenta_AFC', 'Credito_libranza', 'Leasing_confinanciera',
       'Cuenta_movil', 'Libranza_movil', 'Credito_movil',
       'Productos_de_Inversion', 'MasterCard_MIGRAC_MCD', 'Davipay',
       'Nanocredito', 'Bancos_sin_oficina', 'Covid', 'Token_edificios',
       'Credito_de_vehiculo_movil', 'Credito_compra_cartera_movil',
       'Credito_vivienda_movil', 'Credito_Compra_Cartera_Móvil_Libranza',
       'Soat_Digital', 'Fondo_virtual_nomina', 'Otros_call_fallas',
       'Redirigido_oficina', 'Tarjeta de Crédito', 'Crédito fijo',
       'Canales virtuales', 'Tarjeta Débito', 'Crédito hipotecario',
       'Cuenta móvil', 'Libranza móvil', 'Otros Call y fallas',
       'Vehiculo Movil', 'Adelanto de nómina', 'Vivienda Móvil',
       'Banco sin oficinas', 'Compra de cartera Móvil', 'Soat Digital',
       'Fondo virtual', 'Redireccionado a oficina',
       'MasterCard MIGRAC MCD', 'Canales virtuales ',
       'Cuentas de ahorros tradicional y corriente ',
       'Crédito de libre inversión', 'Información y/o servicios',
       'DaviPlata', 'Crédito hipotecario y leasing',
       'Adelanto de nómina ', 'Crédito de vehículo', 'Fallas', 'Calls',
       'CDT(CDAT,Móvil)', 'Crédito libranza',
       'Producto digital Falla en apertura',
       'Producto digital Acompañamiento apertura', 'Biometría facial',
       'Cuentas de ahorros tradicional y corriente', 'Call Internal B'],
      dtype=object)

### SI DESEA CONCATENENAR LOS NUEVOS MESES
## 1. CARGA

In [ ]:

#df2022_11=pd.read_excel(kernel +'11 Tabulación PN - Noviembre 2022.xlsx',sheet_name='Base')
# df2022_12=pd.read_excel(kernel +'12 Tabulación PN - Diciembre 2022.xlsx',sheet_name='Base')
# df2023_1...

## 2. CRUCE
+ ejemplo de cruce

In [ ]:
#df=concat([     df   ,    df2022_11    ],axis=0) 
#df

## 3. FILTROS

In [10]:
# asigna el valor de 1 en toda la columna creada 'interacciones' 
df['Interacciones']=1

### 3.1 Producto y Motivos

In [12]:
agru1 = df.groupby([df['Año'],df['MesN'], df['Producto'],
      df['Motivos']],dropna=False,as_index=False)['Interacciones'].count()

### 3.2 Producto

In [13]:
agru2 = df.groupby([df['Año'],df['MesN'], df['Producto']],
    dropna=False,as_index=False)['Interacciones'].count()

###  3.3 Motivos

In [14]:
agru3 = df.groupby([df['Año'],df['MesN'], df['Motivos']],
    dropna=False,as_index=False)['Interacciones'].count()

### Guardar resumen

In [15]:
agru1.to_excel(kernelB+'RESUMEN_PRODUCTO_&_MOTIVOS_2018-2022.xlsx')
agru2.to_excel(kernelB+'RESUMEN_PRODUCTO_2018-2022.xlsx')
agru3.to_excel(kernelB+'RESUMEN_MOTIVOS_2018-2022.xlsx')

In [16]:
agru1

,Año,MesN,Producto,Motivos,Interacciones
0,2018,6,CDT - CDAT,"Aclaración Saldos, Movimientos y estado de Pro...",1
1,2018,6,CDT - CDAT,"Aclaración saldos, movimientos",18
2,2018,6,CDT - CDAT,"Aclaración saldos, movimientos y estado de pro...",3
3,2018,6,CDT - CDAT,"Acompañamiento autogestión (reporte viajero, t...",6
4,2018,6,CDT - CDAT,"Certificaciones, extractos y paz y salvos",2
...,...,...,...,...,...
35048,2022,10,Tarjeta de Crédito,Pago mínimo o deuda total aclaración - SV,3606
35049,2022,10,Tarjeta de Crédito,Redención o consulta puntos y millas - SV,751
35050,2022,10,Tarjeta de Crédito,Rediferido o cambio de diferido - SV,1694
35051,2022,10,Tarjeta de Crédito,Saldos y movimientos aclaración - SV,4508
35052,2022,10,Tarjeta de Crédito,Tarjeta móvil información general y/o fallas - SV,366

In [17]:
agru2

       Año  MesN                            Producto  Interacciones
0     2018     6                          CDT - CDAT            116
1     2018     6               Crediexpress Rotativo           1467
2     2018     6                       Credito Móvil             38
3     2018     6                 Credíto Hipotecario            805
4     2018     6                 Crédito de Libranza            509
...    ...   ...                                 ...            ...
1537  2022    10  Producto digital Falla en apertura             22
1538  2022    10              Productos de Inversión            538
1539  2022    10                             Seguros           2035
1540  2022    10                      Tarjeta Débito           6202
1541  2022    10                  Tarjeta de Crédito          61481

[1542 rows x 4 columns]

In [18]:
agru3

,Año,MesN,Motivos,Interacciones
0,2018,6,A solicitud del cliente,55
1,2018,6,"Aclaración Saldos, Movimientos",9134
2,2018,6,"Aclaración Saldos, Movimientos y estado de Pro...",2878
3,2018,6,Aclaración reto - no gestionables conservación,86
4,2018,6,"Aclaración saldos, movimientos",3580
...,...,...,...,...
11249,2022,10,Teléfono rojo pagos,8
11250,2022,10,Teléfono rojo recargas,3
11251,2022,10,Teléfono rojo transferencias,65
11252,2022,10,Transfiya / consulta de movimiento - SV,75
11253,2022,10,Vehículo móvil,1

## Filtro para estados de variables especificos
* sensible a mayusculas, tildes, espacios

In [19]:
agru1K=agru1[ (agru1['Año'] == 2022) & (agru1['MesN'] == 10)  & (agru1['Producto']== 'Adelanto de nómina')]
agru1K

,Año,MesN,Producto,Motivos,Interacciones
34796,2022,10,Adelanto de nómina,Cancelación producto - SV,46
34797,2022,10,Adelanto de nómina,Estado del producto - SV,549
34798,2022,10,Adelanto de nómina,Información General - Apertura de Productos- A...,364
34799,2022,10,Adelanto de nómina,Pago mínimo o deuda total aclaración - SV,583
34800,2022,10,Adelanto de nómina,Saldos y movimientos aclaración - SV,58

In [ ]:
#GUARDAR
#agru1K.to_excel(kernelB+'FILTRO_1K.xlsx')

## Filtro para palabra especifica (mas flexible) en motivos o producto


+  str.contains()     una cadena de texto específica
+  str.startswith()   una cadena de texto específica al principio de una columna 
+  str.endswith()     una cadena de texto específica al final de una columna
+  str.match()        busca un patrón de texto específico dentro de una columna


Todas siguen los mismos PARAMETROS:


+  pat (str): La cadena de texto que se busca en la columna.
+ case (bool): Si es True, la búsqueda será sensible a mayúsculas y minúsculas.
 Si es False, la búsqueda no tendrá en cuenta mayúsculas y minúsculas.
+ na (bool): Si es True, los valores NaN se tratarán como coincidencias. Si es False, los valores NaN no se tendrán en cuenta.


________________________________________________________________________
+ flags (int): Una bandera para indicar cómo se realiza la búsqueda.
  
  + re.IGNORECASE: Esta bandera indica que la búsqueda no tendrá en cuenta mayúsculas y minúsculas.
  + re.MULTILINE: Esta bandera indica que la búsqueda se realizará en múltiples líneas.
  + re.DOTALL: Esta bandera indica que el punto (.) coincidirá con cualquier carácter.
  + re.UNICODE: Esta bandera indica que la búsqueda se realizará con caracteres Unicode.
  + re.VERBOSE: Esta bandera indica que la búsqueda se realizará con una sintaxis más legible.

In [21]:
fil=agru1[agru1
  ['Motivos']
  .str.contains('proDuCTo', case=False, na=True)]
fil

,Año,MesN,Producto,Motivos,Interacciones
0,2018,6,CDT - CDAT,"Aclaración Saldos, Movimientos y estado de Pro...",1
2,2018,6,CDT - CDAT,"Aclaración saldos, movimientos y estado de pro...",3
6,2018,6,CDT - CDAT,Consulta e Información de productos - no gesti...,2
11,2018,6,CDT - CDAT,Informacion general / caracteristicas del prod...,2
17,2018,6,Crediexpress Rotativo,"Aclaración Saldos, Movimientos y estado de Pro...",57
...,...,...,...,...,...
35025,2022,10,Tarjeta Débito,Master debit (errores del producto) - SV,48
35032,2022,10,Tarjeta de Crédito,Bloqueo productos por fraude o solicitud clien...,2191
35033,2022,10,Tarjeta de Crédito,Cancelación producto - SV,10002
35046,2022,10,Tarjeta de Crédito,Estado del producto - SV,14722
35047,2022,10,Tarjeta de Crédito,Información General - Apertura de Productos - ...,5581

## BUSCAR MULTIPLES PALABRAS SEPARADAS POR |

In [20]:
fil=agru1[agru1
  ['Motivos']
  .str.contains('celación|cancelacion', case=False, na=True)]
fil

,Año,MesN,Producto,Motivos,Interacciones
31,2018,6,Crediexpress Rotativo,Cancelacion con poder,6
32,2018,6,Crediexpress Rotativo,Cancelacion de cuentas,1
33,2018,6,Crediexpress Rotativo,Cancelacion de productos sin saldo Dafuturo,2
34,2018,6,Crediexpress Rotativo,Cancelación,49
35,2018,6,Crediexpress Rotativo,Cancelación de productos,2
...,...,...,...,...,...
34878,2022,10,Crediexpress Rotativo,Cancelación producto - SV,188
34930,2022,10,Cuentas de ahorros tradicional y corriente,Cancelación producto - SV,780
34945,2022,10,Cuentas de ahorros tradicional y corriente,Cancelación producto - SV,15
35011,2022,10,Productos de Inversión,Cancelación producto - SV,73
35033,2022,10,Tarjeta de Crédito,Cancelación producto - SV,10002

* guardar

In [ ]:
fil.to_excel(kernelB + 'filtro.xlsx')

In [26]:
fil=agru1[agru1
  ['Motivos']
  .str.contains('cancelacion', case=False,na=True)]
fil

,Año,MesN,Producto,Motivos,Interacciones
31,2018,6,Crediexpress Rotativo,Cancelacion con poder,6
32,2018,6,Crediexpress Rotativo,Cancelacion de cuentas,1
33,2018,6,Crediexpress Rotativo,Cancelacion de productos sin saldo Dafuturo,2
46,2018,6,Crediexpress Rotativo,Cobros administrativos- cancelacion,180
50,2018,6,Crediexpress Rotativo,Crediexpress pyme especial - cancelacion,5
...,...,...,...,...,...
32096,2022,5,Redireccionado a oficina,Cancelacion masiva de cuentas,2
32827,2022,6,Redireccionado a oficina,"Cancelacion Ctas (AFC, Niños, Ahorro programad...",2
33536,2022,7,Redireccionado a oficina,Cancelacion masiva de cuentas,1
34244,2022,8,Redireccionado a oficina,"Cancelacion Ctas (AFC, Niños, Ahorro programad...",8
34245,2022,8,Redireccionado a oficina,Cancelacion masiva de cuentas,1

In [25]:
FILEX=agru1[agru1['Producto'].str.contains('EXpRESs',case=False,na=True)]
FILEX

,Año,MesN,Producto,Motivos,Interacciones
16,2018,6,Crediexpress Rotativo,"Aclaración Saldos, Movimientos",133
17,2018,6,Crediexpress Rotativo,"Aclaración Saldos, Movimientos y estado de Pro...",57
18,2018,6,Crediexpress Rotativo,Aclaración reto - no gestionables conservación,1
19,2018,6,Crediexpress Rotativo,"Aclaración saldos, movimientos",129
20,2018,6,Crediexpress Rotativo,"Aclaración saldos, movimientos y estado de pro...",31
...,...,...,...,...,...
34881,2022,10,Crediexpress Rotativo,Débito automático marcación y desmarc - SV,10
34882,2022,10,Crediexpress Rotativo,Estado del producto - SV,486
34883,2022,10,Crediexpress Rotativo,Información General - Apertura de Productos - ...,302
34884,2022,10,Crediexpress Rotativo,Pago mínimo o deuda total aclaración - SV,447
34885,2022,10,Crediexpress Rotativo,Saldos y movimientos aclaración - SV,86

## BUSQUEDA EXHAUSTIVA

In [39]:
#año 2022, meses 8 y 10, en columna motivos cancelacion y cancelación, ignora mayusculas o minisculas
FILEXX=agru1[ (agru1['Año'] == 2022) & (agru1['MesN'].isin([4,8,10]))  & (agru1['Motivos'].str.contains('cancelación| canCeLacion',case=False,na=True))]
FILEXX

,Año,MesN,Producto,Motivos,Interacciones
30785,2022,4,Banco sin oficinas,Cancelación de CDT (con envío de efectivo),48
30786,2022,4,Banco sin oficinas,Cancelación de CDT con abono a cuenta,7
30787,2022,4,Banco sin oficinas,Cancelación de cuentas con saldo >$8M PN y pyme,6
30882,2022,4,Crediexpress Rotativo,Cancelación de productos,271
31087,2022,4,Cuenta Corriente,Cancelación cuentas,60
31114,2022,4,Cuenta de ahorros,Cancelación cuentas,1431
31162,2022,4,Cuenta móvil,Cancelación cuentas,16
31199,2022,4,Cuenta_de_ahorros,Cancelación cuentas,2
31213,2022,4,E card,Cancelación Producto,98
31311,2022,4,Otros Call y fallas,Call Conservación Cancelación TC Fase 2,135
31350,2022,4,Productos de Inversión,Información General - Apertura y cancelación d...,23
31422,2022,4,Tarjeta de Crédito,Cancelación de producto,13408
31484,2022,4,Tarjeta movil,Cancelación de producto,4
33715,2022,8,Banco sin oficinas,Cancelación de CDT (con envío de efectivo),131
33716,2022,8,Banco sin oficinas,Cancelación de CDT con abono a cuenta,32
33717,2022,8,Banco sin oficinas,Cancelación de cuentas con saldo >$8M PN y pyme,10
33812,2022,8,Crediexpress Rotativo,Cancelación de productos,229
33996,2022,8,Cuenta Corriente,Cancelación cuentas,36
34023,2022,8,Cuenta de ahorros,Cancelación cuentas,885
34070,2022,8,Cuenta móvil,Cancelación cuentas,8
34108,2022,8,E card,Cancelación Producto,57
34190,2022,8,Otros Call y fallas,Call Conservación Cancelación TC Fase 2,156
34229,2022,8,Productos de Inversión,Información General - Apertura y cancelación d...,24
34296,2022,8,Tarjeta de Crédito,Cancelación de producto,10708
34356,2022,8,Tarjeta movil,Cancelación de producto,2
34796,2022,10,Adelanto de nómina,Cancelación producto - SV,46
34801,2022,10,Adelanto de nómina,Cancelación producto - SV,3
34810,2022,10,"CDT(CDAT,Móvil)",CDT Cancelación e intereses - SV,154
34811,2022,10,"CDT(CDAT,Móvil)",Cancelación producto - SV,120
34855,2022,10,Calls,"Call conservación - cancelación, exoneración y...",1820
34856,2022,10,Calls,"Call conservación - cancelación, exoneración y...",161
34878,2022,10,Crediexpress Rotativo,Cancelación producto - SV,188
34930,2022,10,Cuentas de ahorros tradicional y corriente,Cancelación producto - SV,780
34945,2022,10,Cuentas de ahorros tradicional y corriente,Cancelación producto - SV,15
35011,2022,10,Productos de Inversión,Cancelación producto - SV,73
35033,2022,10,Tarjeta de Crédito,Cancelación producto - SV,10002

# Directamente de la base original

In [36]:
df2=df[df['Producto'].str.contains('EXPRESS',case=False,na=True)]

In [38]:
agru111 = df2.groupby([df2['Año'],df2['MesN'], df2['Producto'],
      df2['Motivos']],dropna=False,as_index=False)['Interacciones'].count()
agru111

,Año,MesN,Producto,Motivos,Interacciones
0,2018,6,Crediexpress Rotativo,"Aclaración Saldos, Movimientos",133
1,2018,6,Crediexpress Rotativo,"Aclaración Saldos, Movimientos y estado de Pro...",57
2,2018,6,Crediexpress Rotativo,Aclaración reto - no gestionables conservación,1
3,2018,6,Crediexpress Rotativo,"Aclaración saldos, movimientos",129
4,2018,6,Crediexpress Rotativo,"Aclaración saldos, movimientos y estado de pro...",31
...,...,...,...,...,...
2484,2022,10,Crediexpress Rotativo,Débito automático marcación y desmarc - SV,10
2485,2022,10,Crediexpress Rotativo,Estado del producto - SV,486
2486,2022,10,Crediexpress Rotativo,Información General - Apertura de Productos - ...,302
2487,2022,10,Crediexpress Rotativo,Pago mínimo o deuda total aclaración - SV,447
2488,2022,10,Crediexpress Rotativo,Saldos y movimientos aclaración - SV,86

* guardar

In [ ]:
agru111.to_excel(kernelB +'filtro2.xlsx')