In [1]:
import pandas as pd
import numpy as np

In [2]:
dfaa=pd.read_csv('C:/Users/miavila/Desktop/CRUCE SCORE/DICIEMBRE/cruce chat_base &  Clientes.csv')

In [5]:
dfaa.cliente_bancario.unique()
dfaa['CLIENTE']=dfaa['cliente_bancario']

In [6]:
dfaa.CLIENTE.replace('NO','SI',inplace=True)

In [7]:
dfaa.CLIENTE.replace(np.nan,'NO',inplace=True)

In [8]:

dfaa.loc[(dfaa['cliente_bancario'] != 'NO')]

,Unnamed: 0,Fecha,Cola,Conclusión,Cedula,Manejo total,Mes,cliente_bancario,segmento_digital,score_integral,CLIENTE
0,0,2022-02-25 22:04:00,Chat Persona Natural Publica,Información General - Características de produ...,NaN,00:06:07.203,2,NaN,NaN,NaN,NO
1,1,2022-02-25 22:10:00,Chat Persona Natural Publica,Información General - Características de produ...,NaN,00:04:00.544,2,NaN,NaN,NaN,NO
2,2,2022-02-26 00:01:00,Chat Persona Natural Publica,Proceso de apertura de cuentas pensionados - SV,NaN,00:14:51.130,2,NaN,NaN,NaN,NO
3,3,2022-02-26 00:48:00,Chat Persona Natural Publica; Chat Persona Nat...,Monitoreo desbloqueo de productos - SV; Apertu...,NaN,01:47:55.877,2,NaN,NaN,NaN,NO
4,4,2022-02-26 02:08:00,Chat Persona Natural Publica,Saldos y movimientos aclaración - SV,NaN,00:17:10.013,2,NaN,NaN,NaN,NO
...,...,...,...,...,...,...,...,...,...,...,...
1503877,1503877,2022-11-30 23:52:00,Chat Persona Natural Privada,"Clave virtual - asignación, bloqueo y desbloqu...",2.840308e+07,00:10:57.836,11,SI,SIN SEGMENTO,6.0,SI
1503878,1503878,2022-11-30 23:53:00,Chat Persona Natural Publica,"Clave virtual - asignación, bloqueo y desbloqu...",1.128394e+09,00:11:27.068,11,SI,ANALOGO,7.0,SI
1503879,1503879,2022-11-30 23:53:00,Chat Persona Natural Privada,NaN,1.016110e+09,NaN,11,SI,DIGITAL,6.0,SI
1503880,1503880,2022-11-30 23:54:00,Chat Persona Natural Privada; Chat Persona Nat...,Actualización de datos - SV,1.004598e+09,00:12:58.333,11,SI,DIGITAL,5.0,SI
1503881,1503881,2022-11-30 23:55:00,Chat Persona Natural Publica,Cliente nunca escribió - SV,1.050945e+09,00:05:10.376,11,SI,DIGITAL,6.0,SI

In [9]:
dfaa['inter']=1

In [15]:
dfaa.columns

Index(['Unnamed: 0', 'Fecha', 'Cola', 'Conclusión', 'Cedula', 'Manejo total',
       'Mes', 'cliente_bancario', 'segmento_digital', 'score_integral'],
      dtype='object')

In [10]:
agru1K=dfaa[ (dfaa['Mes'] == 9) ]
agru1K

,Unnamed: 0,Fecha,Cola,Conclusión,Cedula,Manejo total,Mes,cliente_bancario,segmento_digital,score_integral,CLIENTE,inter
23454,23454,2022-09-01 00:44:00,Chat Persona Natural Publica,Estado del producto - SV,NaN,00:14:37.106,9,NaN,NaN,NaN,NO,1
23455,23455,2022-09-01 01:09:00,Chat Persona Natural Publica,Clave virtual - olvido y bloqueo - SV,NaN,00:19:06.283,9,NaN,NaN,NaN,NO,1
23456,23456,2022-09-01 09:34:00,Chat Persona Natural Publica,Acompañamiento en canales virtuales (paso a paso),NaN,00:08:05.397,9,NaN,NaN,NaN,NO,1
23457,23457,2022-09-01 12:36:00,Chat Persona Natural Publica,Atribuciones cuentas - SV,NaN,00:11:51.346,9,NaN,NaN,NaN,NO,1
23458,23458,2022-09-01 16:21:00,Chat Persona Natural Publica,Clave virtual - olvido y bloqueo - SV,NaN,00:19:22.379,9,NaN,NaN,NaN,NO,1
...,...,...,...,...,...,...,...,...,...,...,...,...
1276938,1276938,2022-09-30 23:48:00,Chat Persona Natural Privada; Chat Persona Nat...,NaN,1.010061e+09,NaN,9,SI,DIGITAL,5.0,SI,1
1276940,1276940,2022-09-30 23:53:00,Chat Persona Natural Privada; Chat Persona Nat...,Saldos y movimientos aclaración - SV,1.006148e+09,00:09:06.299,9,SI,DIGITAL,4.0,SI,1
1276941,1276941,2022-09-30 23:53:00,Chat Persona Natural Privada; Chat Persona Nat...,Saldos y movimientos aclaración - SV,1.006148e+09,00:09:06.299,9,SI,DIGITAL,4.0,SI,1
1276943,1276943,2022-09-30 23:57:00,Chat Persona Natural Privada,Saldos y movimientos aclaración - SV,5.284073e+07,00:06:33.532,9,SI,DIGITAL,7.0,SI,1
1276944,1276944,2022-09-30 23:57:00,Chat Persona Natural Privada,Saldos y movimientos aclaración - SV,5.284073e+07,00:06:33.532,9,SI,DIGITAL,7.0,SI,1

In [15]:
agru1K.Cedula.count(),agru1K.Cedula.nunique(), 191107-184906

(184906, 126171, 6201)

In [ ]:
agru1K.to_excel('C:/Users/miavila/Desktop/CRUCE SCORE/DICIEMBRE/cruce_mes_SEP.xlsx')

In [5]:
agru = dfaa.groupby([dfaa['Mes'], dfaa['cliente_bancario'],
      dfaa[ 'score_integral']],dropna=False,as_index=False)['inter'].sum()

In [6]:
agru

     Mes cliente_bancario score_integral  inter
0      2              NaN            NaN   6957
1      3               NO           10.0     16
2      3               NO           11.0      9
3      3               NO            2.0      3
4      3               NO            3.0      8
..   ...              ...            ...    ...
220   11               SI            7.0  27299
221   11               SI            8.0  22542
222   11               SI            9.0  15510
223   11               SI      SIN SCORE   9614
224   11              NaN            NaN    100

[225 rows x 4 columns]

In [7]:
agru.to_excel('C:/Users/miavila/Desktop/CRUCE SCORE/DICIEMBRE/cruce_mes_cliente_score.xlsx')

In [8]:
agru = dfaa.groupby([dfaa['Mes'], dfaa['cliente_bancario'],
      dfaa[ 'score_integral'],dfaa['Cola'],dfaa['Conclusión']],dropna=False,as_index=False)['inter'].sum()

In [9]:
agru.inter.sum()

1503882

In [10]:
agru

,Mes,cliente_bancario,score_integral,Cola,Conclusión,inter
0,2,NaN,NaN,Chat Persona Natural Privada,Abono dirigido - SV,5
1,2,NaN,NaN,Chat Persona Natural Privada,Acompañamiento en canales virtuales (paso a paso),120
2,2,NaN,NaN,Chat Persona Natural Privada,Acompañamiento en canales virtuales (paso a pa...,2
3,2,NaN,NaN,Chat Persona Natural Privada,Acompañamiento en canales virtuales (paso a pa...,2
4,2,NaN,NaN,Chat Persona Natural Privada,Actualización de datos - SV,11
...,...,...,...,...,...,...
56246,11,NaN,NaN,Chat Persona Natural Publica; Chat Persona Nat...,Acompañamiento en canales virtuales (paso a paso),2
56247,11,NaN,NaN,Chat Persona Natural Publica; Chat Persona Nat...,Atribuciones cuentas - SV,1
56248,11,NaN,NaN,Chat Persona Natural Publica; Chat Persona Nat...,Cliente nunca escribió - SV,1
56249,11,NaN,NaN,Chat Persona Natural Publica; Chat Persona Nat...,Estado del producto - SV,1
56250,11,NaN,NaN,Chat Persona Natural Publica; Chat Persona Nat...,Información General - Características de produ...,1

In [11]:
agru.to_excel('C:/Users/miavila/Desktop/CRUCE SCORE/DICIEMBRE/cruce_mes_cliente_score_cola_conclusión.xlsx')

In [12]:
agru = dfaa.groupby([dfaa['Mes'], dfaa['cliente_bancario'],
      dfaa['segmento_digital']],dropna=False,as_index=False)['inter'].sum()

In [13]:
agru

    Mes cliente_bancario segmento_digital  inter
0     2              NaN              NaN   6957
1     3               NO          ANALOGO     91
2     3               NO          DIGITAL    312
3     3               NO        ESCEPTICO    168
4     3               NO       MULTICANAL      2
..  ...              ...              ...    ...
91   11               SI          DIGITAL  99687
92   11               SI        ESCEPTICO  11766
93   11               SI       MULTICANAL    166
94   11               SI     SIN SEGMENTO  40217
95   11              NaN              NaN    100

[96 rows x 4 columns]

In [14]:
agru.to_excel('C:/Users/miavila/Desktop/CRUCE SCORE/DICIEMBRE/cruce_mes_cliente_segmento.xlsx')

In [34]:
DFNO=dfaa.loc[(dfaa['cliente_bancario'] != 'SI')]

In [39]:
DFNO

,Unnamed: 0,Fecha,Cola,Conclusión,Cedula,Manejo total,Mes,cliente_bancario,segmento_digital,score_integral,inter
0,0,2022-02-25 22:04:00,Chat Persona Natural Publica,Información General - Características de produ...,NaN,00:06:07.203,2,NaN,NaN,NaN,1
1,1,2022-02-25 22:10:00,Chat Persona Natural Publica,Información General - Características de produ...,NaN,00:04:00.544,2,NaN,NaN,NaN,1
2,2,2022-02-26 00:01:00,Chat Persona Natural Publica,Proceso de apertura de cuentas pensionados - SV,NaN,00:14:51.130,2,NaN,NaN,NaN,1
3,3,2022-02-26 00:48:00,Chat Persona Natural Publica; Chat Persona Nat...,Monitoreo desbloqueo de productos - SV; Apertu...,NaN,01:47:55.877,2,NaN,NaN,NaN,1
4,4,2022-02-26 02:08:00,Chat Persona Natural Publica,Saldos y movimientos aclaración - SV,NaN,00:17:10.013,2,NaN,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...
1503819,1503819,2022-11-30 22:41:00,Chat Persona Natural Publica,"Atribuciones Cuentas(Reintegro o ajustes, cobr...",1.040367e+09,00:28:13.838,11,NO,SIN SEGMENTO,5.0,1
1503828,1503828,2022-11-30 22:44:00,Chat Persona Natural Privada; Chat Persona Nat...,Master debit (solicitud y agendamiento) - SV,1.113314e+09,00:21:31.201,11,NO,SIN SEGMENTO,5.0,1
1503831,1503831,2022-11-30 22:45:00,Chat Persona Natural Publica,Marcación o demarcación 4x1000 - SV,3.023254e+07,00:10:03.976,11,NO,SIN SEGMENTO,5.0,1
1503845,1503845,2022-11-30 22:59:00,Chat Persona Natural Publica,Daviplata- Rappipay - SV,1.084790e+09,00:06:41.844,11,NO,SIN SEGMENTO,5.0,1
1503866,1503866,2022-11-30 23:24:00,Chat Persona Natural Privada,Biometría F - Registro de dispositivo - SV,1.015457e+09,00:08:19.845,11,NO,SIN SEGMENTO,5.0,1

In [35]:
DFSI=dfaa.loc[(dfaa['cliente_bancario'] == 'SI')]

In [36]:
len(DFNO), 'no', len(DFSI),'SI'

(140309, 'no', 1363573, 'SI')

In [29]:
agru = dfaa.groupby([dfaa['Mes'], dfaa['cliente_bancario'],
      dfaa['segmento_digital'],dfaa['Conclusión']],dropna=False,as_index=False)['inter'].sum()

In [37]:
agru.to_excel('C:/Users/miavila/Desktop/CRUCE SCORE/DICIEMBRE/cruce_mes_cliente_segmento_conclusión.xlsx')

In [38]:
DFNO.to_excel('C:/Users/miavila/Desktop/CRUCE SCORE/DICIEMBRE/NO_CLIENTES.xlsx')

In [97]:
DFSI.to_csv('C:/Users/miavila/Desktop/CRUCE SCORE/DICIEMBRE/SI_CLIENTES.csv')

In [22]:
agru = dfaa.groupby([dfaa['Mes'], dfaa['Cola'],dfaa['Conclusión'],dfaa[ 'Cedula'], 
      dfaa['cliente_bancario'], dfaa['segmento_digital'],dfaa[ 'score_integral']],as_index=False)['Cedula'].count()

,Mes,Cola,Conclusión,cliente_bancario,segmento_digital,score_integral,Cedula
0,3,Chat Persona Natural Privada,AFC novedades y traslado entre bancos - SV,SI,DIGITAL,12.0,1.534800e+07
1,3,Chat Persona Natural Privada,AFC novedades y traslado entre bancos - SV,SI,DIGITAL,12.0,1.937276e+07
2,3,Chat Persona Natural Privada,AFC novedades y traslado entre bancos - SV,SI,DIGITAL,13.0,3.978624e+07
3,3,Chat Persona Natural Privada,AFC novedades y traslado entre bancos - SV,SI,DIGITAL,11.0,4.397896e+07
4,3,Chat Persona Natural Privada,AFC novedades y traslado entre bancos - SV,SI,DIGITAL,12.0,5.242552e+07
...,...,...,...,...,...,...,...
1290745,11,Chat Persona Natural Publica; Piloto Chat Llam...,Saldos y movimientos aclaración - SV; Call Bac...,SI,DIGITAL,8.0,1.010229e+09
1290746,11,Chat Persona Natural Publica; Piloto Chat Llam...,Saldos y movimientos aclaración - SV; Call Bac...,SI,DIGITAL,8.0,1.082248e+09
1290747,11,Chat Persona Natural Publica; Piloto Chat Llam...,Saldos y movimientos aclaración - SV; Call Bac...,SI,ESCEPTICO,7.0,1.098804e+09
1290748,11,Chat Persona Natural Publica; USO Monitoreo,"Alertamientos monitoreo, se remite cliente a l...",SI,DIGITAL,11.0,1.017153e+09
1290749,11,Chat Persona Natural Publica; USO Monitoreo,Cliente sin requerimiento - SV; Estado del pro...,SI,DIGITAL,8.0,1.128408e+09

In [ ]:
AG.index= range(AG.shape[0])